# Generated by Django 2.0.2 on 2018-04-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='recovery_id',
        ),
    ]
