# Generated by Django 2.0.2 on 2018-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180406_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='A Question', max_length=100),
            preserve_default=False,
        ),
    ]
